---
sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - displaymanager
    - networkcfg
    - hwclock
    - grubcfg
    - bootloader
    - remove
    - postinstall
  - show:
    - finished

branding: irisos
prompt-install: false
dont-chroot: false
disable-cancel: false
disable-cancel-during-exec: false

